ARG php_version=8.3
ARG node_version=22

### Stage 1: Node Build Environment
FROM node:${node_version}-alpine as nodebuilder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

### Stage 2: CraftCMS + PHP (Queue Worker)
FROM craftcms/nginx:${php_version}

USER root

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apk add --no-cache git unzip bash vim mariadb-connector-c mysql-client

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install --no-interaction --no-dev --optimize-autoloader

COPY --from=nodebuilder /app/web/dist /app/web/dist

COPY . .

RUN mkdir -p /app/storage /app/web/cpresources /app/web/assets \
  && chown -R www-data:www-data /app/config /app/storage /app/web/cpresources /app/web/assets /app/.env \
  && chmod -R 775 /app/config /app/storage /app/web/cpresources /app/web/assets /app/.env

USER www-data

ENTRYPOINT []
CMD ["php", "craft", "queue/listen", "--verbose"]
