defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cd17b7ef-0947-48a6-8b71-1e366fa396e8 # Default Pagebuilder
handle: news
maxAuthors: 2
minAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  1723a27b-575b-4f9f-86ce-78e2bf638980: # English
    enabledByDefault: true
    hasUrls: true
    template: /pages/_entry.twig
    uriFormat: 'news/{slug}'
  ca23fe3a-c532-4ee4-9497-b7748360de16: # Deutsch
    enabledByDefault: false
    hasUrls: true
    template: /pages/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
